# training_configurations




dataloader:
  num_workers: 8
  batch_size: 8

dataset:
  name: 'sen12'
  root_dir: '../../dataset/sen12_categorized'
  seed: 42

model:
  name: 'unet'

train:
  device: 'cuda'
  lr: 1e-3
  weight_decay: 1e-4
  
  