# training_configurations

device: 'cuda'
seed: 114514

dataset:
  name: 'sen12'
  root_dir: '../../dataset/sen12_categorized'
  split_ratio: [0.8, 0.1, 0.1]


dataloader:
  num_workers: 8
  batch_size: 8


model:
  name: 'unet'
  num_res_blocks: 3
  num_channels: 64

flow:
  sigma_min: 1e-4
  eval_steps: 50

train:
  epochs: 5000
  min_lr: 1e-4
  max_lr: 1e-4
  weight_decay: 1e-4
  accumulate_steps: 2
  # warmup_steps: 1000
  # max_steps: 400000
  

valid:
  valid_interval: 10
  sample_num: 40
  sample_interval: 10
  dt_schedule: 'linear'
  integrate_method: 'odeint'